
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Archivos_sHTTP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SITIOS = 4;
  public static final int SITIO = 3;
  public static final int PAGINA = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PAGINAS = 6;
  public static final int PAGINASITIOS = 7;
  public static final int GET = 8;
  public static final int POST = 2;
  public static final int PATCH = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "POST",
  "SITIO",
  "SITIOS",
  "PAGINA",
  "PAGINAS",
  "PAGINASITIOS",
  "GET",
  "PATCH"
  };
}

