
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores_1.notebookmovil.Backend.ArchivoCodigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 4;
  public static final int DECIMAL = 3;
  public static final int MENOS = 8;
  public static final int POT = 11;
  public static final int UMENOS = 14;
  public static final int ENTERO = 2;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int PAR2 = 13;
  public static final int PAR1 = 12;
  public static final int DIV = 10;
  public static final int SALTO = 5;
  public static final int error = 1;
  public static final int MUL = 9;
  public static final int IMPRIMIR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "SALTO",
  "IMPRIMIR",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "POT",
  "PAR1",
  "PAR2",
  "UMENOS"
  };
}

