
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores_1.notebookmovil.Backend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 16;
  public static final int MENOS = 9;
  public static final int ENCABEZADO = 3;
  public static final int TEXTO = 2;
  public static final int SUMA = 8;
  public static final int EOF = 0;
  public static final int INDICE = 6;
  public static final int PAR2 = 15;
  public static final int TEXTOCONFORMATO = 5;
  public static final int NUMERO = 4;
  public static final int PAR1 = 14;
  public static final int DIV = 11;
  public static final int error = 1;
  public static final int PRINT = 13;
  public static final int MUL = 10;
  public static final int TEXTO_PARRAFO = 7;
  public static final int INICIOCADENA = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXTO",
  "ENCABEZADO",
  "NUMERO",
  "TEXTOCONFORMATO",
  "INDICE",
  "TEXTO_PARRAFO",
  "SUMA",
  "MENOS",
  "MUL",
  "DIV",
  "INICIOCADENA",
  "PRINT",
  "PAR1",
  "PAR2",
  "DECIMAL"
  };
}

