[pagina_1]
nombre: "pagina 1"
tipo: pagina
path: "src/paginaSitios/pagina_1.mtsx"
[sitio_1]
nombre: "sitio 1"
tipo: sitio
path: "src/paginaSitios/sitio_1"
[sitio_1.pagina_1]
nombre: "pagina 1"
tipo: paginaSitio
path: "src/paginaSitios/sitio_1/pagina_1.mtsx"
[sitio_1.pagina_2]
nombre: "pagina 2"
tipo: paginaSitio
path: "src/paginaSitios/sitio_1/pagina_2.mtsx"
[sitio_1.pagina_3]
nombre: "pagina 3"
tipo: paginaSitio
path: "src/paginaSitios/sitio_1/pagina_3.mtsx"
[sitio_2]
nombre: "sitio 2"
tipo: sitio
path: "src/paginaSitios/sitio_2"
[sitio_2.mi_pagina]
nombre: "mi pagina"
tipo: paginaSitio
path: "src/paginaSitios/sitio_2/mi_pagina.mtsx"
[sitio_2.pagina_2]
nombre: "pagina 2"
tipo: paginaSitio
path: "src/paginaSitios/sitio_2/pagina_2.mtsx"
[pagiba_2]
nombre: "pagiba 2"
tipo: pagina
path: "src/paginaSitios/pagiba_2.mtsx"
[mi_pagina_de_ejmplo]
nombre: "mi pagina de ejmplo"
tipo: pagina
path: "src/paginaSitios/mi_pagina_de_ejmplo.mtsx"
[mi_sitio_compi]
nombre: "mi sitio compi"
tipo: sitio
path: "src/paginaSitios/mi_sitio_compi"
[mi_sitio_compi.pagina1]
nombre: "pagina1"
tipo: paginaSitio
path: "src/paginaSitios/mi_sitio_compi/pagina1.mtsx"
[la_pagina_de_melvin]
nombre: "la pagina de melvin"
tipo: pagina
path: "src/paginaSitios/la_pagina_de_melvin.mtsx"
[sitio_1.power]
nombre: "power"
tipo: paginaSitio
path: "src/paginaSitios/sitio_1/power.mtsx"
[sitio_prueba]
nombre: "sitio prueba"
tipo: sitio
path: "src/paginaSitios/sitio_prueba"
[sitio_prueba.melvin]
nombre: "melvin"
tipo: paginaSitio
path: "src/paginaSitios/sitio_prueba/melvin.mtsx"
