[pagina_1]
nombre: "pagina 1"
tipo: pagina
path: "src/paginaSitios/pagina_1.mtsx"
[mi_sitio_1]
nombre: "mi sitio 1"
tipo: sitio
path: "src/paginaSitios/mi_sitio_1"
[mi_sitio_1.ss]
nombre: "ss"
tipo: paginaSitio
path: "src/paginaSitios/mi_sitio_1/ss.mtsx"
[mi_sitio_1.mi_pagina_1]
nombre: "mi pagina 1"
tipo: paginaSitio
path: "src/paginaSitios/mi_sitio_1/mi_pagina_1.mtsx"
[mi_sitio_1.pagina_1]
nombre: "pagina 1"
tipo: paginaSitio
path: "src/paginaSitios/mi_sitio_1/pagina_1.mtsx"
