package Fronted;

import Backend.Modificar;
import Backend.Obtener;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author carlos
 */
public class PanelEditorPagina extends javax.swing.JPanel {

    int ancho;
    int alto;
    String contenidoEntrada="";
    String nombre="";

    /**
     * Creates new form PanelEditorPagina
     */
    public PanelEditorPagina(int ancho, int alto) {
        this.alto = alto;
        this.ancho = ancho;
        String nombre="";
        initComponents();

        try {

            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            setBounds(0, 0, ancho, alto);
            contenedor.setBounds(0, 0, ancho, alto);

            jPanel1.setBounds(0, 0, (int) ((ancho * 0.2)), alto);
            jScrollPane1.setBounds((int) ((ancho * 0.3)), (int) ((alto * 0.05)), (int) ((ancho * 0.6)), (int) ((alto * 0.7)));
            jButton1.setBounds(0, (int) ((alto * 0.20)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
            jButton2.setBounds(0, (int) ((alto * 0.35)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
            jButton3.setBounds((int) ((ancho * 0.05)), (int) ((alto * 0.85)), (int) ((ancho * 0.1)), (int) ((alto * 0.05)));
            jLabel1.setBounds(0, 0, (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void obtnerPagina(String nombre) {
        this.nombre=nombre;
        Obtener obtener=new Obtener();
        
        String contenido="\n"+obtener.obtenerContenidoPagina(nombre);
        Editor.setText(contenido);
        this.contenidoEntrada=contenido;
    }

    public void setNombrePagina(String nombrePagina) {
        jLabel1.setText(nombrePagina);

    }

    public void cambiarEstado() {

        panelAnterior.setVisible(true);
    }
    JPanel panelAnterior;

    public void panel(JPanel panel) {
        panelAnterior = panel;
    }

    public void restablecerBotonces(int boton) {

        if (boton != 1) {
            jButton1.setBounds(0, (int) ((alto * 0.20)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
            jButton1.setBackground(Color.decode("#2c495b"));
            jButton1.setForeground(Color.decode("#FDF7E7"));

           
        }

        if (boton != 2) {
            jButton2.setBounds(0, (int) ((alto * 0.35)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
            jButton2.setBackground(Color.decode("#2c495b"));
            jButton2.setForeground(Color.decode("#FDF7E7"));

           
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Editor = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(253, 247, 231));
        setLayout(null);

        contenedor.setBackground(new java.awt.Color(253, 247, 231));
        contenedor.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(44, 73, 91));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(44, 73, 91));
        jButton1.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 247, 231));
        jButton1.setText("Analizar");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 200, 250, 35);

        jButton2.setBackground(new java.awt.Color(44, 73, 91));
        jButton2.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(253, 247, 231));
        jButton2.setText("Guardar");
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 290, 250, 35);

        jLabel1.setBackground(new java.awt.Color(42, 76, 86));
        jLabel1.setFont(new java.awt.Font("P052", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 238, 223));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 120, 170, 30);

        jButton3.setBackground(new java.awt.Color(253, 247, 231));
        jButton3.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 73, 91));
        jButton3.setText("Cancelar");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 640, 250, 35);

        contenedor.add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 730);

        Editor.setBackground(new java.awt.Color(253, 247, 231));
        Editor.setColumns(20);
        Editor.setFont(new java.awt.Font("C059", 2, 18)); // NOI18N
        Editor.setRows(5);
        Editor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 73, 91), 7, true));
        jScrollPane1.setViewportView(Editor);

        contenedor.add(jScrollPane1);
        jScrollPane1.setBounds(390, 50, 640, 450);

        add(contenedor);
        contenedor.setBounds(0, 0, 1070, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Modificar modificar=new Modificar();
        
        modificar.AnalisarCodigo(nombre, Editor.getText());
        
        jButton2.setEnabled(true);
        jButton1.setBounds(0, (int) ((alto * 0.20)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
        jButton1.setBackground(Color.decode("#FDF7E7"));
        jButton1.setForeground(Color.decode("#2c495b"));
        restablecerBotonces(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if (Editor.getText().equals(this.contenidoEntrada)) {
            System.out.println(this.nombre);
             
        }else{
            jButton2.setEnabled(false);
             JOptionPane.showMessageDialog(null, "Se notaron cambios en el codigo, nesecita analizarlo antes de guardar", "Minimal React", JOptionPane.INFORMATION_MESSAGE);
             
        }
        
        jButton2.setBounds(0, (int) ((alto * 0.35)), (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
        jButton2.setBackground(Color.decode("#FDF7E7"));
        jButton2.setForeground(Color.decode("#2c495b"));
        restablecerBotonces(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cambiarEstado();
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Editor;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
