package Fronted;

import Backend.Agregar;
import Backend.Crear;
import Backend.Obtener;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author carlos
 */
public class PanelEdicionSitios extends javax.swing.JPanel {
private PanelEditorPagina editorPagina;
    Agregar agregar = new Agregar();
    String nombre;
    Obtener obtener = new Obtener();
    int ancho;
    int alto;
    private JScrollPane scrollPaginas;

    /**
     * Creates new form PanelEdicionSitios
     */
    public PanelEdicionSitios(int ancho, int alto) {
        this.alto = alto;
        this.ancho = ancho;

        initComponents();

        try {

            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            setBounds(0, 0, ancho, alto);
            editorPagina = new PanelEditorPagina(ancho, alto);
            add(editorPagina);
            editorPagina.setVisible(false);
            contenedor.setBounds(0, 0, ancho, alto);
            jButton1.setBounds(0, (int) ((alto * 0.15)), (int) ((ancho * 0.2)), (int) ((alto * 0.05)));
            jPanel1.setBounds(0, 0, (int) ((ancho * 0.2)), alto);
            jButton3.setBounds((int) ((ancho * 0.05)), (int) ((alto * 0.9)), (int) ((ancho * 0.1)), (int) ((alto * 0.05)));
            jLabel1.setBounds(0, 0, (int) ((ancho * 0.2)), (int) ((alto * 0.1)));
            scrollPaginas = new JScrollPane(panelBotonesPaginas);
            scrollPaginas.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPaginas.setBounds(0, (int) (alto * 0.23), (int) (ancho * 0.2), (int) (alto * 0.65));
            jPanel1.add(this.scrollPaginas);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setNombrePagina(String nombrePagina) {
        jLabel1.setText(nombrePagina);

    }

    public void cambiarEstado() {

        panelAnterior.setVisible(true);
    }
    JPanel panelAnterior;

    public void panel(JPanel panel) {
        panelAnterior = panel;
    }

    public void mostrarPaginas() {
        panelBotonesPaginas.removeAll();
        ArrayList<String> paginas = obtener.obtenerPaginasSitio(jLabel1.getText());

        for (int i = 0; i < paginas.size(); i++) {
            JButton boton = new JButton();
            boton.setText(paginas.get(i));

            boton.setBackground(Color.decode("#2c495b"));
            boton.setForeground(Color.decode("#FDF7E7"));
            boton.setFont(new Font("P052", Font.BOLD | Font.ITALIC, 24));
            boton.setHorizontalAlignment(SwingConstants.CENTER);
            boton.setVerticalAlignment(SwingConstants.CENTER);

            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setContentAreaFilled(true);

            boton.setBounds(0, (int) ((alto * 0.06)) * (i), (int) ((ancho * 0.2)), (int) ((alto * 0.05)));
            String nombre = boton.getText();

            boton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    System.out.println("hoal");
                    panelEdicionPAgina(nombre);

                }
            });
            panelBotonesPaginas.add(boton);
            int alturaTotal = (int) (alto * 0.06) * paginas.size();
            panelBotonesPaginas.setPreferredSize(new Dimension((int) (ancho * 0.19), alturaTotal));

            panelBotonesPaginas.revalidate();
            panelBotonesPaginas.repaint();
            panelBotonesPaginas.updateUI();
        }

    }

    public void panelEdicionPAgina(String nombre) {
        contenedor.setVisible(false);
        editorPagina.panel(contenedor);
        editorPagina.setVisible(true);
         editorPagina.setNombrePagina(nombre);
        editorPagina.obtnerPagina(jLabel1.getText() + "," + nombre);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelBotonesPaginas = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        contenedor.setBackground(new java.awt.Color(253, 247, 231));
        contenedor.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(44, 73, 91));
        jPanel1.setLayout(null);

        panelBotonesPaginas.setBackground(new java.awt.Color(44, 73, 91));

        javax.swing.GroupLayout panelBotonesPaginasLayout = new javax.swing.GroupLayout(panelBotonesPaginas);
        panelBotonesPaginas.setLayout(panelBotonesPaginasLayout);
        panelBotonesPaginasLayout.setHorizontalGroup(
            panelBotonesPaginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelBotonesPaginasLayout.setVerticalGroup(
            panelBotonesPaginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.add(panelBotonesPaginas);
        panelBotonesPaginas.setBounds(20, 180, 270, 300);

        jButton3.setBackground(new java.awt.Color(253, 247, 231));
        jButton3.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 73, 91));
        jButton3.setText("Cancelar");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 630, 250, 35);

        jButton1.setBackground(new java.awt.Color(44, 73, 91));
        jButton1.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 247, 231));
        jButton1.setText("Crear pagina");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 100, 250, 35);

        jLabel1.setBackground(new java.awt.Color(253, 247, 231));
        jLabel1.setFont(new java.awt.Font("P052", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 73, 91));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 30, 170, 30);

        contenedor.add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 730);

        add(contenedor);
        contenedor.setBounds(0, 0, 990, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cambiarEstado();
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nombre = "";
        while (nombre == null || nombre.isEmpty()) {
            nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre de su pagina:", "Minimal React", JOptionPane.INFORMATION_MESSAGE);

            if (nombre == null) {
                JOptionPane.showMessageDialog(null, "Se ha cancelado la creación de su pagina", "Minimal React", JOptionPane.CANCEL_OPTION);
                return;
            }

            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El nombre de la pagina es requerido.", "Minimal React", JOptionPane.WARNING_MESSAGE);
            }
        }
        if (agregar.agregarPagina(jLabel1.getText() + "," + nombre)) {
            JOptionPane.showMessageDialog(null, "Su pagina a sido agregada", agregar.response(), JOptionPane.INFORMATION_MESSAGE);
            mostrarPaginas();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotonesPaginas;
    // End of variables declaration//GEN-END:variables
}
