package Fronted;

import javax.swing.UIManager;

/**
 *
 * @author carlos
 */
public class PanelPrincipal extends javax.swing.JPanel {
    
    PanelCreacion panelCreacion;
    PanelEdicion panelEdicion;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(int ancho, int alto) {
        initComponents();
        jPanel3.setBounds(0, 0, ancho, alto);
        panelCreacion = new PanelCreacion(ancho, alto);
        panelEdicion=new PanelEdicion(ancho, alto);
        add(panelCreacion);
        add(panelEdicion);
        panelCreacion.setVisible(false);
       
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            setBounds(0, 0, ancho, alto);
            jLabel1.setBounds(0, 0, (int) (ancho - (ancho * 0.30)), alto);
            jLabel3.setBounds(0, (int) ((alto * 0.02)), (int) ((ancho * 0.5)), (int) ((alto * 0.2) / 2));
            jLabel2.setBounds(0, (int) ((alto * 0.2) / 2), (int) ((ancho * 0.5)), (int) ((alto * 0.2) / 2));
            jButton1.setBounds((int) ((ancho * 0.05)), (int) ((alto * 0.15)), (int) ((ancho * 0.25)), (int) ((alto * 0.1)));
            jButton2.setBounds((int) ((ancho * 0.05)), (int) ((alto * 0.35)), (int) ((ancho * 0.25)), (int) ((alto * 0.1)));
            jButton3.setBounds((int) ((ancho * 0.05)), (int) ((alto * 0.55)), (int) ((ancho * 0.25)), (int) ((alto * 0.1)));
            jButton4.setBounds((int) ((ancho * 0.2)), (int) ((alto * 0.75)), (int) ((ancho * 0.10)), (int) ((alto * 0.1)));
            jPanel2.setBounds((int) ((ancho * 0.1)), (int) ((alto * 0.4)), (int) ((ancho * 0.5)), (int) ((alto * 0.2)));
            FondosDeEtiquetas.fondo2(jLabel1);
            jPanel1.setBounds((int) (ancho - (ancho * 0.30)), 0, (int) ((ancho * 0.30)), alto);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 247, 231));
        setLayout(null);

        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(44, 73, 91));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(42, 76, 86));
        jLabel2.setFont(new java.awt.Font("P052", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 238, 223));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CMS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 90, 300, 80);

        jLabel3.setBackground(new java.awt.Color(42, 76, 86));
        jLabel3.setFont(new java.awt.Font("P052", 3, 90)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 238, 223));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reac Minimal");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 80);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(110, 150, 510, 170);

        jPanel1.setBackground(new java.awt.Color(44, 73, 91));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(252, 252, 232));
        jButton1.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(44, 73, 91));
        jButton1.setText("Modo Creacion");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 90, 250, 35);

        jButton2.setBackground(new java.awt.Color(252, 252, 232));
        jButton2.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(44, 73, 91));
        jButton2.setText("Modo Edicion");
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 90, 250, 35);

        jButton3.setBackground(new java.awt.Color(252, 252, 232));
        jButton3.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 73, 91));
        jButton3.setText("Modo Visualizacion");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 20, 250, 35);

        jButton4.setBackground(new java.awt.Color(252, 252, 232));
        jButton4.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(44, 73, 91));
        jButton4.setText("Salir");
        jButton4.setToolTipText("");
        jButton4.setBorderPainted(false);
        jButton4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 50, 250, 35);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(230, 20, 420, 140);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(90, 20, 107, 92);

        add(jPanel3);
        jPanel3.setBounds(0, 0, 100, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanel3.setVisible(false);
       panelCreacion.panel(jPanel3);
       panelCreacion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jPanel3.setVisible(false);
       panelEdicion.panel(jPanel3);
       panelEdicion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
