package Fronted;

import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.LineBorder;

/**
 *
 * @author carlos
 */
public class Panelnicio extends javax.swing.JPanel {

    /**
     * Creates new form Panelnicio
     *
     * @param ancho
     * @param alto
     */
    PanelPrincipal panelPrincipal;

    public Panelnicio(int ancho, int alto) {
        initComponents();
        try {
            jPanel1.setBounds(0,0,ancho,alto);
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
             panelPrincipal=new PanelPrincipal(ancho,alto);
               add(panelPrincipal);
               panelPrincipal.setVisible(false);
            setBounds(0, 0, ancho, alto);
            
            jLabel1.setBounds(0, 0, ancho, (int) (alto - (alto * 0.02)));
            FondosDeEtiquetas.portada(jLabel1);
            jButton1.setBounds((int) (ancho - 250 - (ancho * 0.05)), (int) (alto - 35 - (alto * 0.1)), 250, 35);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 51));
        setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(46, 74, 95));
        jButton1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(252, 252, 232));
        jButton1.setText("Iniciar");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1110, 660, 250, 35);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 0, 0);
        jLabel1.setBounds(500, 300, 700, 60);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
        panelPrincipal.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
